services:
  timescaledb:
    build:
      context: .
      dockerfile: dockerfile.timescaledb
    container_name: timescaledb_container
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  timescaledb_data:
  redis_data:
    driver: local
