services:
  - type: web
    name: trading-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: StocksDB
          property: connectionString
  - type: worker
    name: scheduler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scheduler.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: StocksDB
          property: connectionString
